# test1

### Тест №1:  Проверка на два действительных корня (позитивный)
- Цель: проверить вычисление квадратного уравнения с двмуя различными действительными корнями.
- Входные данные: a = 1, b = -5, c = 6
- Ожимаемый результат: два корня. root1 = 3.0, root2 = 2.0
- Описание процесса: вызов функции find_roots(1, -5, 6) должен вернуть кортеж с двумя корнями. Результат проверяется на соответствие ожидаемому.

### Тест №2: Проверка на один действительный корень (дискриминант равен нулю) (позитивный)
- Цель: проверить вычисление квадратного уравнения с одним действительным корнем.
- Входные данные: a = 1, b = -4, c = 4
- Ожимаемый результат: один корень. root = 2.0
- Описание процесса: вызов функции find_roots(1, -4, 4) должен вернуть кортеж с одним корнем. Результат проверяется на соответствие ожидаемому.

### Тест №3: Проверка на комплексные корни (позитивный)
- Цель: проверить вычисление квадратного уравнения с двумя комплексными корнями.
- Входные данные: a = 1, b = -2, c = 5
- Ожимаемый результат: два комплексных корня. root1 = (1+2j), root2 = (1-2j)
- Описание процесса: вызов функции find_roots(1, -2, 5) должен вернуть кортеж с двумя комплексными корнями. Результат проверяется на соответствие ожидаемому.

### Тест №4: Проверка обработки первого нулевого коэффициента (негативный)
- Цель: проверить обработку исключения при нулевом первом коэффициенте.
- Входные данные: a = 0, b = 2, c = 3
- Ожимаемый результат: Исключение ValueError с сообщением: "Первый коэффициент не может быть равен нулю для квадратного уравнения"
- Описание процесса: вызов функции find_roots(0, 2, 3) должен вызвать исключение ValueError. Результат проверяется на соответствие ожидаемому сообщению об ошибке.

### Тест №5: Проверка на невалидные типы данных (негативный)
- Цель: проверить, что функция find_roots корректно обрабатывает ситуацию, когда передаются коэффициенты некорректного типа.
- Входные данные: a = "aaaaaaaaaa", b = 2, c = 3
- Ожимаемый результат: Исключение TypeError с сообщением: "Коэффициенты должны быть числами".
- Описание процесса: вызов функции find_roots(aaaaaaaaaa, 2, 3) должен вызвать исключение ValueError. Результат проверяется на соответствие ожидаемому сообщению об ошибке.

### Тест №6: Проверка функции с большими коэффициентами (позитивный)
- Цель: проверить, что функция find_roots корректно обрабатывает ситуацию, когда передаются коэффициенты некорректного типа.
- Входные данные: a = 9000000, b = 8000000, c = 7000000
- Ожимаемый результат: получены два корня (вещественные или комплексные)
- Описание процесса: вызов функции find_roots(9000000, 8000000, 7000000) должен вернуть кортеж с двумя корнями. Результат проверяется на соответствие ожидаемому.

